# Basic Numpy 

*The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.* [(link)](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

![](resource/numpy.png)

- **Size** - Numpy data structures take up less space
- **Performance** - they have a need for speed and are faster than lists
- **Functionality** - SciPy and NumPy have optimized functions such as linear algebra operations built in.

Download **Numpy Cheat Sheet** from datacamp [(Download)](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

In [1]:
import numpy as np

In [11]:
np.__version__

'1.16.5'

### Create 1D Vector

In [2]:
# vector baris (axis 0)

vector_row = np.array([1,2,3,4,5,6])

print(vector_row)


[1 2 3 4 5 6]


- Check dimesion of vector /matrix using `.shape`

In [3]:
print(vector_row.shape)

(6,)


In [4]:
type(vector_row)

numpy.ndarray

In [5]:
# vector kolom (axis 1)

vector_column = np.array([[1],[2],[3], [4], [5], [6]])

print(vector_column)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [6]:
print(vector_column.shape)

(6, 1)


### Create 2D Vector (Matrix)

In [7]:
matrix = np.array([[1,2,3,5],
                   [4,5,6,6],
                   [7,8,9,9]])
#[[1,2,3],
# [4,5,6]]

print(matrix)

[[1 2 3 5]
 [4 5 6 6]
 [7 8 9 9]]


In [8]:
matrix.shape

(3, 4)

In [9]:
type(matrix)

numpy.ndarray

### Create Matrix Zero
`np.zeros((3,4))` *Create an array of zeros*


In [10]:
zero_matrix = np.zeros(100)

print(zero_matrix)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [11]:
zero_matrix = np.zeros(6, 2)

print(zero_matrix)

TypeError: Cannot interpret '2' as a data type

In [ ]:
zero_matrix = np.zeros((6, 2)) # 6 baris, 2 kolom

print(zero_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
zero_matrix = np.zeros((2, 6)) # 2 baris, 6 kolom

print(zero_matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [13]:
zero_matrix = np.zeros((5, 7)) # 5 baris, 7 kolom

print(zero_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [14]:
zero_matrix = np.zeros((4, 5, 2)) # 4 baris, 5 kolom, 2 kedalaman

print(zero_matrix)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


### Create Matrix One
`np.ones((2,3,4),dtype=np.int16)` *Create an array of ones*

In [15]:
one_matrix = np.ones(60)

print(one_matrix)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
one_matrix = np.ones((4, 9)) # 4 baris, 9 kolom

print(one_matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
one_matrix = np.ones((9, 4)) # 9 baris, 4 kolom

print(one_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Generate Matrix
`np.linspace(0,2,9)` *Create an array of evenly*

In [18]:
generated_matrix = np.linspace(1,5)  # default 50 item, generate from 1 to 5

In [19]:
print(generated_matrix)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [20]:
generated_matrix = np.linspace(1,5,3)
print(generated_matrix)

[1. 3. 5.]


In [21]:
generated_matrix = np.linspace(1,5,5)
print(generated_matrix)

[1. 2. 3. 4. 5.]


In [22]:
generated_matrix = np.linspace(0,5,6)
print(generated_matrix)

[0. 1. 2. 3. 4. 5.]


In [23]:
generated_matrix = np.linspace(0,10,3)
print(generated_matrix)

[ 0.  5. 10.]


### Akses elemen Vector

In [24]:
matrix

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [25]:
matrix[1] # akses baris index 1

array([4, 5, 6, 6])

In [26]:
matrix[-1] # akses baris index -1 (baris paling akhir)

array([7, 8, 9, 9])

- akses menggunakan slice

In [27]:
matrix[1:] # akses baris index 1 & 2

array([[4, 5, 6, 6],
       [7, 8, 9, 9]])

In [28]:
matrix[0:2] # akses baris index 0 & 1

array([[1, 2, 3, 5],
       [4, 5, 6, 6]])

In [29]:
matrix[-2:-1] # akses baris index 1 & 2

array([[4, 5, 6, 6]])

- mengakses kolom dalam matrix 2D

In [30]:
myList = [[1, 2, 3], [4, 5, 6]]

myList[0]

[1, 2, 3]

In [31]:
myList[0][1]

2

In [32]:
matrix

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [33]:
matrix[:, -1] # akses kolom index -1

array([5, 6, 9])

In [34]:
matrix[:, 1] # akses kolom index 1

array([2, 5, 8])

In [35]:
matrix[:, 2:] # akses kolom index 2 & 3 

array([[3, 5],
       [6, 6],
       [9, 9]])

In [36]:
matrix[:, 2:3]

array([[3],
       [6],
       [9]])

In [37]:
matrix #akses [5, 6, 6]

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [38]:
matrix[1, 1:]

array([5, 6, 6])

In [39]:
#akses [[1, 2, 3]
#       [4, 5, 6]]

In [40]:
matrix[0:2, 0:3]

array([[1, 2, 3],
       [4, 5, 6]])

- Matrix 3D (baris, kolom, kedalaman)

In [41]:
matrix = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   
                   [[7, 8, 9],
                    [10,11,12]]])

In [42]:
matrix[0] # akses baris ke 0

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
matrix[1] # akses baris ke 1

array([[ 7,  8,  9],
       [10, 11, 12]])

In [44]:
matrix[0, 1] # akses baris ke 0, kolom ke 1

array([4, 5, 6])

In [45]:
matrix[1, 1] # akses baris ke 1, kolom ke 1

array([10, 11, 12])

In [46]:
matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
matrix[1, 1, 1:] # akses baris ke 1, kolom ke 1, kedalaman ke 1 & 2

array([11, 12])

In [48]:
matrix[1, 1, 0:2] # akses baris ke 1, kolom ke 1, kedalaman ke 0 & 1

array([10, 11])

In [49]:
matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
# akses elemen [3, 6]
matrix[0, :, -1] # akses baris ke 0

array([3, 6])

In [51]:
# akses elemen [8, 11]
matrix[1, :, 1] # akses baris ke 0

array([ 8, 11])

In [52]:
# akses elemen [[1, 4], [7, 10]]
matrix[:, :, 0] # akses baris ke 0

array([[ 1,  4],
       [ 7, 10]])

In [53]:
# akses elemen [[3, 6], [9, 12]]

In [54]:
matrix[:, :, -1]

array([[ 3,  6],
       [ 9, 12]])

- [Task] complex case **3D Matrix**, access elemen [9,9]

In [55]:
matrix = np.array([[[1, 2, 3, 5, 5],
                    [4, 5, 6, 6, 6]],
                   
                   [[7, 8, 9, 9, 10],
                    [1, 3, 3, 1, 0 ]]])

In [56]:
matrix.shape

(2, 2, 5)

In [57]:
# jawaban


#

In [58]:
matrix[1, 0, 2:4]

array([9, 9])

- [Task] complex case 3D Matrix, access elemen [1, 3, 3]

In [59]:
# jawaban


#

In [60]:
matrix[1, 1, :3]

array([1, 3, 3])

### Vector Data Type

In [61]:
matrix = np.array([[ 1,  2,  3,  5,  5],
                   [ 4,  5,  6,  6,  6],
                   [ 7,  8,  9,  9, 10]])

In [62]:
matrix.dtype

dtype('int64')

In [63]:
matrix = matrix.astype(np.uint16)

In [64]:
matrix.dtype

dtype('uint16')

In [65]:
matrix.nbytes

30

In [66]:
matrix = matrix.astype(np.int32)

In [67]:
matrix.dtype

dtype('int32')

In [68]:
matrix.nbytes

60

In [69]:
matrix = matrix.astype(np.uint8)

In [70]:
matrix.dtype

dtype('uint8')

In [71]:
matrix.nbytes

15

In [72]:
matrix

array([[ 1,  2,  3,  5,  5],
       [ 4,  5,  6,  6,  6],
       [ 7,  8,  9,  9, 10]], dtype=uint8)

### Describe Vector

In [73]:
matrix = np.array([[ 1,  2,  3,  5,  5],
                   [ 4,  5,  6,  6,  6],
                   [ 7,  8,  9,  9, 10]])

In [74]:
matrix.shape # baris, kolom

(3, 5)

In [75]:
matrix.shape[0]

3

In [76]:
matrix.shape[1]

5

In [77]:
matrix.size

15

In [78]:
matrix.ndim

2

In [79]:
vec = np.array([1, 2, 3])

vec.ndim

1

### Builtin Function

In [80]:
matrix

array([[ 1,  2,  3,  5,  5],
       [ 4,  5,  6,  6,  6],
       [ 7,  8,  9,  9, 10]])

In [81]:
np.max(matrix)

np.int64(10)

In [82]:
matrix.max()

np.int64(10)

In [83]:
np.min(matrix)

np.int64(1)

In [84]:
matrix.min()

np.int64(1)

In [85]:
np.mean(matrix)

np.float64(5.733333333333333)

In [86]:
matrix.mean()

np.float64(5.733333333333333)

In [87]:
np.median(matrix)

np.float64(6.0)

In [88]:
np.std(matrix)

np.float64(2.515728301881761)

In [89]:
matrix.std()

np.float64(2.515728301881761)

In [90]:
np.var(matrix)

np.float64(6.328888888888889)

In [91]:
matrix.var()

np.float64(6.328888888888889)

In [92]:
np.power(matrix, 3)

array([[   1,    8,   27,  125,  125],
       [  64,  125,  216,  216,  216],
       [ 343,  512,  729,  729, 1000]])

In [93]:
np.sqrt(matrix)

array([[1.        , 1.41421356, 1.73205081, 2.23606798, 2.23606798],
       [2.        , 2.23606798, 2.44948974, 2.44948974, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.        , 3.16227766]])

In [94]:
matrix

array([[ 1,  2,  3,  5,  5],
       [ 4,  5,  6,  6,  6],
       [ 7,  8,  9,  9, 10]])

In [95]:
np.amax(matrix, axis=1) # 1 : kolom, 0 : baris

array([ 5,  6, 10])

In [96]:
np.amin(matrix, axis=1) # 1 : kolom, 0 : baris

array([1, 4, 7])

In [97]:
np.argmax(matrix, axis=1) # 1 : kolom, 0 : baris

array([3, 2, 4])

In [98]:
np.argmin(matrix, axis=1) # 1 : kolom, 0 : baris

array([0, 0, 0])

### Reshape Matrix

In [99]:
matrix = np.array([[1,2,3,5],
                   [4,5,6,6],
                   [7,8,9,9]])

print(matrix)

[[1 2 3 5]
 [4 5 6 6]
 [7 8 9 9]]


In [100]:
matrix.shape

(3, 4)

In [101]:
np.reshape(matrix, (4,3))

array([[1, 2, 3],
       [5, 4, 5],
       [6, 6, 7],
       [8, 9, 9]])

In [102]:
np.reshape(matrix, (3,2,2))

array([[[1, 2],
        [3, 5]],

       [[4, 5],
        [6, 6]],

       [[7, 8],
        [9, 9]]])

In [103]:
np.reshape(matrix, (12,1))

array([[1],
       [2],
       [3],
       [5],
       [4],
       [5],
       [6],
       [6],
       [7],
       [8],
       [9],
       [9]])

In [104]:
matrix 

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [105]:
np.reshape(matrix, (6,2))

array([[1, 2],
       [3, 5],
       [4, 5],
       [6, 6],
       [7, 8],
       [9, 9]])

### Matrix Operation

In [106]:
A = np.array([[1, 3, 1],
              [5, 2, 1]])

B = np.array([[0, 0, 1],
              [3, 5, 1]])

#### Penjumlahan Matrix

![](resource/penjumlahan_matrix.PNG)

In [107]:
A + B

array([[1, 3, 2],
       [8, 7, 2]])

In [108]:
A - B

array([[ 1,  3,  0],
       [ 2, -3,  0]])

#### Perkalian Skalar

![](resource/perkalian_scalar_matrix.PNG)

In [109]:
2 * A

array([[ 2,  6,  2],
       [10,  4,  2]])

In [110]:
3.5 * B

array([[ 0. ,  0. ,  3.5],
       [10.5, 17.5,  3.5]])

In [111]:
1 / A

array([[1.        , 0.33333333, 1.        ],
       [0.2       , 0.5       , 1.        ]])

In [112]:
mtr = np.array([0, 0])

1/mtr

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10740\3812170609.py:3: RuntimeWarning: divide by zero encountered in divide
  1/mtr


array([inf, inf])

In [113]:
B / 2

array([[0. , 0. , 0.5],
       [1.5, 2.5, 0.5]])

#### Perkalian matrix biasa

$\begin{bmatrix} 1 & 3 & 1 \\ 5 & 2 & 1 \end{bmatrix} \begin{bmatrix} 0 & 0 & 1 \\ 3 & 5 & 1 \end{bmatrix} = \begin{bmatrix} 1\times0 & 1\times0 & 1\times1 \\ 5\times3 & 2\times5 & 1\times1 \end{bmatrix} = \begin{bmatrix} 0 & 0 & 1 \\ 15 & 10 & 1 \end{bmatrix}$

In [114]:
A*B

array([[ 0,  0,  1],
       [15, 10,  1]])

In [115]:
B/A

array([[0. , 0. , 1. ],
       [0.6, 2.5, 1. ]])

In [116]:
2 * B / A

array([[0. , 0. , 2. ],
       [1.2, 5. , 2. ]])

#### Transpose Matrix

![](resource/transpose_matrix.PNG)

In [117]:
A

array([[1, 3, 1],
       [5, 2, 1]])

In [118]:
ATranspose = np.transpose(A)

ATranspose

array([[1, 5],
       [3, 2],
       [1, 1]])

In [119]:
np.transpose(ATranspose)

array([[1, 3, 1],
       [5, 2, 1]])

In [120]:
A.T

array([[1, 5],
       [3, 2],
       [1, 1]])

#### Matrix multiplication (dot product)

![](resource/dot_product.PNG)

- hanya dapat dilakukan jika dan hanya jika jumlah kolom pada matrix kiri sama dengan jumlah baris pada matrix kanan. \
$(M, n)(n, m)$ \
untuk, 
$(M, n)$ merupakan ukuran matrix dibagian kanan, \
$(n, m)$ merupakan ukuran matrix dibagian kiri, \
dan akan menghasilkan matrix dengan ukuran $(M, m)$


- Contoh :


$X = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$

- size X adalah 2, 3

$Y = \begin{bmatrix} 0 & 3 \\ 5 & 1 \\ 7 & 3\end{bmatrix}$

- size Y adalah 3, 2


- sehingga kedua matrix diatas dapat dilakukan operasi dot untuk size (2, `3`)(`3`, 2)


In [121]:
X = np.array([[1, 2, 1],
              [3, 0, 1]])

Y = np.array([[0, 3, 4, 1],
              [5, 1, 4, 1],
              [7, 3, 4, 1]])

In [122]:
X.shape, Y.shape

((2, 3), (3, 4))

In [123]:
np.dot(X, Y)

array([[17,  8, 16,  4],
       [ 7, 12, 16,  4]])

In [124]:
# (3,4)(2,3)
np.dot(Y, X)

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)

In [125]:
# (3,4)(2,3)
np.dot(Y.T, X.T)

array([[17,  7],
       [ 8, 12],
       [16, 16],
       [ 4,  4]])

In [126]:
Y.T.shape, X.T.shape

((4, 3), (3, 2))

### [Task]
- Buat dua buah 2D matrix (A & B) dengan ukuran masing-masing (4,5) dan (5, 2), dengan menggunakan `np.linspace` & `np.reshape`
- hitung A ⋅ B

In [127]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [128]:
A = np.reshape(np.linspace(1,10,20), (4,5))

In [129]:
A

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

#### Generating Random Value

In [130]:
help(np.random.randint)

Help on method randint in module numpy.random:

randint(low, high=None, size=None, dtype=<class 'int'>) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, o

In [131]:
#Generate 3 random integers b/w 1 and 10
print(np.random.randint(0,17,25))

[ 3 15  0 10 13 10  0  4  5  9  3  5 16  5  5 10  0  0 10  9 12  9  3 14
 13]


In [132]:
help(np.random.normal)

Help on method normal in module numpy.random:

normal(loc=0.0, scale=1.0, size=None) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)

    Draw random samples from a normal (Gaussian) distribution.

    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).

    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.

    .. note::
        New code should use the `~numpy.random.Generator.normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    loc : float or array_li

In [133]:
#Draw 3 numbers from a normal distribution with mean 1.0 and std 0.5
print(np.random.normal(1.0, 0.1, 10))

[1.02432752 0.99120721 1.04970368 1.00055591 1.03021258 0.98081145
 1.0045391  1.06874906 0.96752589 1.1046166 ]
